### ISSUE TITLE
When is the next new releases?

### ISSUE THREAD

**Issue by ivanteoh** [collective/collective.dancing#17]
I wonder when is the next new releases?

**Comment by ivanteoh** [comment]
@dnouri, @tmog, @saily any comment? Thanks.

**Comment by saily** [comment]
Please give us your pypi username so we can add you as maintainer.

**Comment by ivanteoh** [comment]
Great thanks. My pypi username is ivanteoh. To confirm that this release will be 1.0?

**Comment by ivanteoh** [comment]
@saily Quick follow up the status. Did you manage to find my pypi username, ivanteoh?

**Comment by saily** [comment]
@ivanteoh sorry for the late answer, i've added you on pypi as package owner.
