### ISSUE TITLE
Ledger

### ISSUE THREAD

**Issue by stquinn2015** [collective/collective.dancing#19]
Is it possible to force a sales order to be posted automatically to ledger without using batch invoicing using salesInvoicing also can you make a payment using data against a sales order

**Comment by frisi** [comment]
do you want to make dancing work with http://www.ledger-cli.org/?
remember: this primarily is a newsletter tool for the plone content management system.
if you still need help, please update your ticket so it's more specific.
otherwhise we'll close this ticket after 30 days of inactivity
