### ISSUE TITLE
Plone 4.0.9 broken after install of 1.0 (No module named uuid.interfaces)

### ISSUE THREAD

**Issue by mck9** [collective/collective.dancing#23]
Log:

... snip ...
  File "/var/www/plone/plone4/buildout-cache/eggs/collective.dancing-1.0-py2.6.egg/collective/dancing/browser/sendnewsletter.py", line 43, in <module>
    from plone.uuid.interfaces import IUUID
ZopeXMLConfigurationError: File "/var/www/plone/plone4/buildout-cache/eggs/Plone-4.0.9-py2.6.egg/Products/CMFPlone/configure.zcml", line 94.4-98.10
    ZopeXMLConfigurationError: File "/var/www/plone/plone4/buildout-cache/eggs/collective.dancing-1.0-py2.6.egg/collective/dancing/configure.zcml", line 20.2-20.32
    ZopeXMLConfigurationError: File "/var/www/plone/plone4/buildout-cache/eggs/collective.dancing-1.0-py2.6.egg/collective/dancing/browser/configure.zcml", line 211.2-216.7
    ImportError: No module named uuid.interfaces

**Comment by mck9** [comment]
Any chance to see this merged?

**Comment by frisi** [comment]
there is an open question to @saily in https://github.com/collective/collective.dancing/pull/26 
@mck9 maybe you could elaborate how/why plone4.0 tests could pass w/o this change

**Comment by frisi** [comment]
cleaning up the tracker - support for plone >4.3 has been dropped in https://github.com/collective/collective.dancing/commit/d65d0dfc40b256736202c4e22f8b800581712dce
