### ISSUE TITLE
Changing subscriber's email address breaks unsubscribe

### ISSUE THREAD

**Issue by mck9** [collective/collective.dancing#28]
When a subscriber's email address is changed in the channel's subscriptions tab, the new subscriber email address is not able to unsubscribe.
Maybe the field should be read-only?

The logged error:
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module collective.dancing.browser.subscribe, line 147, in **call**
  Module collective.singing.subscribe, line 250, in remove_subscription
  Module zope.container.btree, line 119, in **delitem**
KeyError: u'NEW_EMAIL@ADDRESS'

**Comment by mck9** [comment]
:-)

**Comment by frisi** [comment]
still using s&D marek?

**Comment by mck9** [comment]
Yes, I am. I would love to see it on Plone 5. Don't know if I will find the time...
