### ISSUE TITLE
Use plone's MailHost by default

### ISSUE THREAD

**Issue by frisi** [collective/collective.dancing#5]
collective.dancing should use MailHost by default.
currently developers need to do extra work to enable queued delivery.

MailHost on Plone >= 4.0 is able do use queues, so performance for sending many emails should be fine.

we can add a note to the readme how to configure mailhost to use queued delivery

in addition collective.dancing would play nice with products such as Products.PrintingMailHost in test environments too.

**Comment by displacedaussie** [comment]
This change now been merged. Closing.
